# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\plathe\PycharmProjects\pyjson-converter-gui\pyJSON_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeaderLayout = QtWidgets.QHBoxLayout()
        self.HeaderLayout.setSpacing(2)
        self.HeaderLayout.setObjectName("HeaderLayout")
        self.CurrLayout = QtWidgets.QVBoxLayout()
        self.CurrLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.CurrLayout.setSpacing(2)
        self.CurrLayout.setObjectName("CurrLayout")
        self.CurrSchemLayout = QtWidgets.QHBoxLayout()
        self.CurrSchemLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.CurrSchemLayout.setContentsMargins(-1, -1, -1, 0)
        self.CurrSchemLayout.setSpacing(2)
        self.CurrSchemLayout.setObjectName("CurrSchemLayout")
        self.curr_descr_label2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curr_descr_label2.sizePolicy().hasHeightForWidth())
        self.curr_descr_label2.setSizePolicy(sizePolicy)
        self.curr_descr_label2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.curr_descr_label2.setIndent(5)
        self.curr_descr_label2.setObjectName("curr_descr_label2")
        self.CurrSchemLayout.addWidget(self.curr_descr_label2)
        self.current_schema_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.current_schema_combo_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.current_schema_combo_box.setObjectName("current_schema_combo_box")
        self.CurrSchemLayout.addWidget(self.current_schema_combo_box)
        self.CurrLayout.addLayout(self.CurrSchemLayout)
        self.CurrDirLayout = QtWidgets.QHBoxLayout()
        self.CurrDirLayout.setSpacing(2)
        self.CurrDirLayout.setObjectName("CurrDirLayout")
        self.Curr_dir_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Curr_dir_label.sizePolicy().hasHeightForWidth())
        self.Curr_dir_label.setSizePolicy(sizePolicy)
        self.Curr_dir_label.setMinimumSize(QtCore.QSize(100, 0))
        self.Curr_dir_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Curr_dir_label.setIndent(5)
        self.Curr_dir_label.setObjectName("Curr_dir_label")
        self.CurrDirLayout.addWidget(self.Curr_dir_label)
        self.curr_dir_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.curr_dir_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.curr_dir_comboBox.setObjectName("curr_dir_comboBox")
        self.CurrDirLayout.addWidget(self.curr_dir_comboBox)
        self.CurrLayout.addLayout(self.CurrDirLayout)
        self.CurrJSONLayout = QtWidgets.QHBoxLayout()
        self.CurrJSONLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.CurrJSONLayout.setSpacing(2)
        self.CurrJSONLayout.setObjectName("CurrJSONLayout")
        self.curr_descr_label = QtWidgets.QLabel(self.centralwidget)
        self.curr_descr_label.setMinimumSize(QtCore.QSize(100, 20))
        self.curr_descr_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.curr_descr_label.setIndent(5)
        self.curr_descr_label.setObjectName("curr_descr_label")
        self.CurrJSONLayout.addWidget(self.curr_descr_label)
        self.curr_json_label = QtWidgets.QLabel(self.centralwidget)
        self.curr_json_label.setMinimumSize(QtCore.QSize(0, 20))
        self.curr_json_label.setText("")
        self.curr_json_label.setIndent(5)
        self.curr_json_label.setObjectName("curr_json_label")
        self.CurrJSONLayout.addWidget(self.curr_json_label)
        self.CurrLayout.addLayout(self.CurrJSONLayout)
        self.HeaderLayout.addLayout(self.CurrLayout)
        self.ButtonBarLayout = QtWidgets.QHBoxLayout()
        self.ButtonBarLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.ButtonBarLayout.setContentsMargins(20, -1, 20, -1)
        self.ButtonBarLayout.setSpacing(2)
        self.ButtonBarLayout.setObjectName("ButtonBarLayout")
        self.pushButton_addSchema = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addSchema.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_addSchema.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_addSchema.setObjectName("pushButton_addSchema")
        self.ButtonBarLayout.addWidget(self.pushButton_addSchema)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_search.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_search.setObjectName("pushButton_search")
        self.ButtonBarLayout.addWidget(self.pushButton_search)
        self.pushButton_dirSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dirSel.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_dirSel.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_dirSel.setObjectName("pushButton_dirSel")
        self.ButtonBarLayout.addWidget(self.pushButton_dirSel)
        self.NOSBarLayout = QtWidgets.QHBoxLayout()
        self.NOSBarLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.NOSBarLayout.setContentsMargins(10, -1, 10, -1)
        self.NOSBarLayout.setSpacing(2)
        self.NOSBarLayout.setObjectName("NOSBarLayout")
        self.pushButton_new = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_new.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_new.setObjectName("pushButton_new")
        self.NOSBarLayout.addWidget(self.pushButton_new)
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_open.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_open.setObjectName("pushButton_open")
        self.NOSBarLayout.addWidget(self.pushButton_open)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_save.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_save.setObjectName("pushButton_save")
        self.NOSBarLayout.addWidget(self.pushButton_save)
        self.ButtonBarLayout.addLayout(self.NOSBarLayout)
        self.HeaderLayout.addLayout(self.ButtonBarLayout)
        self.verticalLayout.addLayout(self.HeaderLayout)
        self.TreeView = QtWidgets.QTreeView(self.centralwidget)
        self.TreeView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.TreeView.setObjectName("TreeView")
        self.verticalLayout.addWidget(self.TreeView)
        self.label_curDir = QtWidgets.QLabel(self.centralwidget)
        self.label_curDir.setIndent(5)
        self.label_curDir.setObjectName("label_curDir")
        self.verticalLayout.addWidget(self.label_curDir)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_JSON = QtWidgets.QAction(MainWindow)
        self.actionOpen_JSON.setObjectName("actionOpen_JSON")
        self.actionAdd_Schema = QtWidgets.QAction(MainWindow)
        self.actionAdd_Schema.setObjectName("actionAdd_Schema")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCreate_JSON_from_selected_Schema = QtWidgets.QAction(MainWindow)
        self.actionCreate_JSON_from_selected_Schema.setObjectName("actionCreate_JSON_from_selected_Schema")
        self.actionValidate_input_against_selected_schema = QtWidgets.QAction(MainWindow)
        self.actionValidate_input_against_selected_schema.setObjectName("actionValidate_input_against_selected_schema")
        self.actionSave_as_default = QtWidgets.QAction(MainWindow)
        self.actionSave_as_default.setObjectName("actionSave_as_default")
        self.actionLoad_default_for_selected_schema = QtWidgets.QAction(MainWindow)
        self.actionLoad_default_for_selected_schema.setObjectName("actionLoad_default_for_selected_schema")
        self.actionReload_JSON_and_drop_Changes = QtWidgets.QAction(MainWindow)
        self.actionReload_JSON_and_drop_Changes.setObjectName("actionReload_JSON_and_drop_Changes")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionCheck_indexes = QtWidgets.QAction(MainWindow)
        self.actionCheck_indexes.setObjectName("actionCheck_indexes")
        self.menuFile.addAction(self.actionOpen_JSON)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAdd_Schema)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_default_for_selected_schema)
        self.menuFile.addAction(self.actionSave_as_default)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCheck_indexes)
        self.menuEdit.addAction(self.actionCreate_JSON_from_selected_Schema)
        self.menuEdit.addAction(self.actionValidate_input_against_selected_schema)
        self.menuEdit.addAction(self.actionReload_JSON_and_drop_Changes)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.curr_descr_label2.setText(_translate("MainWindow", "Current Schema:"))
        self.Curr_dir_label.setText(_translate("MainWindow", "Search directory:"))
        self.curr_descr_label.setText(_translate("MainWindow", "Current JSON:"))
        self.pushButton_addSchema.setText(_translate("MainWindow", "addSchema"))
        self.pushButton_search.setText(_translate("MainWindow", "search"))
        self.pushButton_dirSel.setText(_translate("MainWindow", "dirSel"))
        self.pushButton_new.setText(_translate("MainWindow", "new"))
        self.pushButton_open.setText(_translate("MainWindow", "open"))
        self.pushButton_save.setText(_translate("MainWindow", "save"))
        self.label_curDir.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_JSON.setText(_translate("MainWindow", "Open JSON..."))
        self.actionAdd_Schema.setText(_translate("MainWindow", "Add Schema..."))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCreate_JSON_from_selected_Schema.setText(_translate("MainWindow", "Create Blank from selected schema"))
        self.actionValidate_input_against_selected_schema.setText(_translate("MainWindow", "Validate input against selected schema"))
        self.actionSave_as_default.setText(_translate("MainWindow", "Save as default for selected schema"))
        self.actionLoad_default_for_selected_schema.setText(_translate("MainWindow", "Load default for selected schema"))
        self.actionReload_JSON_and_drop_Changes.setText(_translate("MainWindow", "Reload JSON and drop Changes..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionCheck_indexes.setText(_translate("MainWindow", "Check indexes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

