on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: PyTest Code Testing
    env:
      DISPLAY: ":99.0"
      QT_SELECT: "qt6"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install xvfb
        run: |
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          python -m pytest ./Tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html